#!/usr/bin/env python3
"""
Fyller nabokommuner for ALLE kommuner basert på norsk geografi.
Dictionary med alle ~348 kommuner og deres nabokommuner.
"""

import re
from pathlib import Path

# Komplett dictionary med nabokommuner for alle norske kommuner
# Sortert alfabetisk
neighbors = {
    "aalesund": (["volda", "giske", "heroeya"], "Ålesund grenser mot Volda, Giske og Herøy."),
    "afjord": (["osen"], "Åfjord grenser mot Osen."),
    "alstahaug": (["vefsn", "brostoey", "hemnes"], "Alstahaug grenser mot Vefsn, Brønnøy og Hemnes."),
    "alta": (["porsanger", "kautokeino"], "Alta grenser mot Porsanger og Kautokeino."),
    "alvdal": (["tynset", "tolga", "folldal"], "Alvdal grenser mot Tynset, Tolga og Folldal."),
    "alver": (["askoy", "osteroy", "samnanger", "fusa"], "Alver grenser mot Askøy, Osterøy, Samnanger og Fusa."),
    "amli": (["vegaarshei", "gjerstad"], "Åmli grenser mot Vegårshei og Gjerstad."),
    "amot": (["asnes", "valer-innlandet", "trysil", "rendalen"], "Åmot grenser mot Åsnes, Våler, Trysil og Rendalen."),
    "andoy": (["oksnes", "sortland"], "Andøy grenser mot Øksnes og Sortland."),
    "ardal": (["vik"], "Årdal grenser mot Vik."),
    "arendal": (["grimstad", "gjerstad", "froland"], "Arendal grenser mot Grimstad, Gjerstad og Froland."),
    "aremark": (["marker", "valer-ostfold", "halden"], "Aremark grenser mot Marker, Våler og Halden."),
    "aseral": (["kvinesdal"], "Åseral grenser mot Kvinesdal."),
    "askoy": (["bergen", "alver", "os-vestland"], "Askøy grenser mot Bergen, Alver og Bjørnafjorden."),
    "askvoll": (["hyllestad", "fjaler", "sunnfjord"], "Askvoll grenser mot Hyllestad, Fjaler og Sunnfjord."),
    "asnes": (["grue", "kongsvinger", "amot"], "Åsnes grenser mot Grue, Kongsvinger og Åmot."),
    "asker": (["oslo", "barum", "lier", "drammen"], "Asker grenser mot Oslo, Bærum, Lier og Drammen."),
    "aukra": (["vestnes", "sande-more-og-romsdal"], "Aukra grenser mot Vestnes og Sande."),
    "aurland": (["sogndal", "laerdal", "kvam"], "Aurland grenser mot Sogndal, Lærdal og Kvam."),
    "aurskog-holand": (["nes", "nannestad", "hurdal", "eidsvoll"], "Aurskog-Høland grenser mot Nes, Nannestad, Hurdal og Eidsvoll."),
    "austrheim": (["masfjorden", "fedje"], "Austrheim grenser mot Masfjorden og Fedje."),
    "aure": (["smola"], "Aure grenser mot Smøla."),
    "averoy": (["gjemnes", "kristiansund", "hustadvika"], "Averøy grenser mot Gjemnes, Kristiansund og Hustadvika."),
    "ballangen": (["evenes", "tjeldsund"], "Ballangen grenser mot Evenes og Tjeldsund."),
    "balsfjord": (["senja", "malselv", "storfjord"], "Balsfjord grenser mot Senja, Målselv og Storfjord."),
    "bamble": (["skien", "porsgrunn", "krageroe"], "Bamble grenser mot Skien, Porsgrunn og Kragerø."),
    "bardu": (["malselv", "salangen"], "Bardu grenser mot Målselv og Salangen."),
    "barum": (["oslo", "asker", "hole", "ringerike"], "Bærum grenser mot Oslo, Asker, Hole og Ringerike."),
    "batsfjord": (["berlevag", "vadso", "nesseby"], "Båtsfjord grenser mot Berlevåg, Vadsø og Nesseby."),
    "beiarn": (["gildeskal", "steigen"], "Beiarn grenser mot Gildeskål og Steigen."),
    "bergen": (["askoy", "os-vestland", "osteroy", "vaksdal"], "Bergen grenser mot Askøy, Bjørnafjorden, Osterøy og Vaksdal."),
    "berlevag": (["gamvik", "batsfjord"], "Berlevåg grenser mot Gamvik og Båtsfjord."),
    "bindal": (["somna"], "Bindal grenser mot Sømna."),
    "birkenes": (["lillesand", "iveland", "gjerstad"], "Birkenes grenser mot Lillesand, Iveland og Gjerstad."),
    "bjerkreim": (["lund", "gjesdal"], "Bjerkreim grenser mot Lund og Gjesdal."),
    "bjugn": (["skaun", "orkland"], "Bjugn grenser mot Skaun og Orkland."),
    "bokn": (["haugesund", "tysvear"], "Bokn grenser mot Haugesund og Tysvær."),
    "bodo": (["rana", "vefsn", "meloey"], "Bodø grenser mot Rana, Vefsn og Meløy."),
    "bomlo": (["stord", "kvinnherad", "sveio"], "Bømlo grenser mot Stord, Kvinnherad og Sveio."),
    "bremanger": (["kinn", "stad", "gloppen"], "Bremanger grenser mot Kinn, Stad og Gloppen."),
    "brostoey": (["alstahaug", "hemnes", "leirfjord"], "Brønnøy grenser mot Alstahaug, Hemnes og Leirfjord."),
    "bygland": (["evje-og-hornnes", "valle", "bykle"], "Bygland grenser mot Evje og Hornnes, Valle og Bykle."),
    "bykle": (["bygland", "valle"], "Bykle grenser mot Bygland og Valle."),
    "bo-nordland": (["hadsel", "oksnes"], "Bø grenser mot Hadsel og Øksnes."),
    "drangedal": (["krageroe", "nome", "midt-telemark"], "Drangedal grenser mot Kragerø, Nome og Midt-Telemark."),
    "drammen": (["asker", "lier", "kongsberg", "ovre-eiker"], "Drammen grenser mot Asker, Lier, Kongsberg og Øvre Eiker."),
    "dyrøy": (["gratangen", "ibestad"], "Dyrøy grenser mot Gratangen og Ibestad."),
    "donna": (["leirfjord", "heroy-nordland"], "Dønna grenser mot Leirfjord og Herøy."),
    "dovre": (["lom", "skjak", "lesja", "oppdal"], "Dovre grenser mot Lom, Skjåk, Lesja og Oppdal."),
    "eidsberg": (["grue", "asnes"], "Eidsberg grenser mot Grue og Åsnes."),
    "eidskog": (["grue", "nord-odal", "sor-odal", "kongsvinger"], "Eidskog grenser mot Grue, Nord-Odal, Sør-Odal og Kongsvinger."),
    "eidsvoll": (["nes", "ullensaker", "ralingen", "nannestad"], "Eidsvoll grenser mot Nes, Ullensaker, Rælingen og Nannestad."),
    "eigersund": (["sokndal", "lund"], "Eigersund grenser mot Sokndal og Lund."),
    "elverum": (["stor-elvdal", "rendalen", "tynset"], "Elverum grenser mot Stor-Elvdal, Rendalen og Tynset."),
    "enebakk": (["lorenskog", "ski", "ralingen", "lillestrom"], "Enebakk grenser mot Lørenskog, Ski, Rælingen og Lillestrøm."),
    "engerdal": (["tolga", "tynset", "alvdal"], "Engerdal grenser mot Tolga, Tynset og Alvdal."),
    "etne": (["kvinnherad", "sveio"], "Etne grenser mot Kvinnherad og Sveio."),
    "etnedal": (["oystre-slidre", "sor-aurdal"], "Etnedal grenser mot Øystre Slidre og Sør-Aurdal."),
    "evenes": (["loding", "narvik", "tjeldsund"], "Evenes grenser mot Lødingen, Narvik og Tjeldsund."),
    "evje-og-hornnes": (["iveland", "bygland", "valle"], "Evje og Hornnes grenser mot Iveland, Bygland og Valle."),
    "faerder": (["sandefjord", "larvik"], "Færder grenser mot Sandefjord og Larvik."),
    "farsund": (["mandal", "lyngdal", "flekkefjord"], "Farsund grenser mot Mandal, Lyngdal og Flekkefjord."),
    "fauske": (["narvik", "rana", "saltdal"], "Fauske grenser mot Narvik, Rana og Saltdal."),
    "fedje": (["austrheim", "masfjorden"], "Fedje grenser mot Austrheim og Masfjorden."),
    "fitjar": (["tysnes", "sveio"], "Fitjar grenser mot Tysnes og Sveio."),
    "fjaler": (["askvoll", "sunnfjord"], "Fjaler grenser mot Askvoll og Sunnfjord."),
    "fjord": (["orsta", "stranda", "vanylven"], "Fjord grenser mot Ørsta, Stranda og Vanylven."),
    "flaa": (["gol", "hemsedal", "aal"], "Flå grenser mot Gol, Hemsedal og Ål."),
    "flakstad": (["moskenes", "vestvagoy", "vagan"], "Flakstad grenser mot Moskenes, Vestvågøy og Vågan."),
    "flatanger": (["overhalla", "naeroysund"], "Flatanger grenser mot Overhalla og Nærøysund."),
    "flekkefjord": (["farsund", "lyngdal", "sirdal"], "Flekkefjord grenser mot Farsund, Lyngdal og Sirdal."),
    "flesberg": (["krodsherad", "sigdal", "nesbyen", "nore-og-uvdal"], "Flesberg grenser mot Krødsherad, Sigdal, Nesbyen og Nore og Uvdal."),
    "folldal": (["alvdal", "dovre", "lesja"], "Folldal grenser mot Alvdal, Dovre og Lesja."),
    "fredrikstad": (["sarpsborg", "moss", "indre-ostfold", "hvaler"], "Fredrikstad grenser mot Sarpsborg, Moss, Indre Østfold og Hvaler."),
    "frogn": (["nordre-follo", "nesodden", "vestby", "as"], "Frogn grenser mot Nordre Follo, Nesodden, Vestby og Ås."),
    "froland": (["arendal", "grimstad", "gjerstad"], "Froland grenser mot Arendal, Grimstad og Gjerstad."),
    "fusa": (["os-vestland", "vaksdal", "alver"], "Fusa grenser mot Bjørnafjorden, Vaksdal og Alver."),
    "fyresdal": (["tokke", "vinje", "nissedal"], "Fyresdal grenser mot Tokke, Vinje og Nissedal."),
    "gamvik": (["lebesby", "berlevag"], "Gamvik grenser mot Lebesby og Berlevåg."),
    "gausdal": (["lillehammer", "oyer", "ringebu", "os-innlandet"], "Gausdal grenser mot Lillehammer, Øyer, Ringebu og Os."),
    "gjerstad": (["froland", "arendal", "birkenes", "iveland"], "Gjerstad grenser mot Froland, Arendal, Birkenes og Iveland."),
    "gjemnes": (["tingvoll", "averoy"], "Gjemnes grenser mot Tingvoll og Averøy."),
    "gjesdal": (["time", "bjerkreim", "strand"], "Gjesdal grenser mot Time, Bjerkreim og Strand."),
    "giske": (["aalesund", "volda", "orsta", "ulstein", "heroeya"], "Giske grenser mot Ålesund, Volda, Ørsta, Ulstein og Herøy."),
    "gjerdrum": (["ullensaker", "nittedal", "hurdal", "lunner"], "Gjerdrum grenser mot Ullensaker, Nittedal, Hurdal og Lunner."),
    "gjovik": (["gran", "lunner", "ostre-toten", "vestre-toten"], "Gjøvik grenser mot Gran, Lunner, Østre Toten og Vestre Toten."),
    "gloppen": (["bremanger", "stad", "stryn"], "Gloppen grenser mot Bremanger, Stad og Stryn."),
    "gol": (["flaa", "hemsedal", "hol", "nesbyen"], "Gol grenser mot Flå, Hemsedal, Hol og Nesbyen."),
    "gran": (["lunner", "nannestad", "sondre-land", "jevnaker"], "Gran grenser mot Lunner, Nannestad, Søndre Land og Jevnaker."),
    "grane": (["saltdal", "hattfjelldal", "vevelstad"], "Grane grenser mot Saltdal, Hattfjelldal og Vevelstad."),
    "gratangen": (["dyrøy", "ibestad", "lavangen"], "Gratangen grenser mot Dyrøy, Ibestad og Lavangen."),
    "grimstad": (["arendal", "tvedestrand", "froland"], "Grimstad grenser mot Arendal, Tvedestrand og Froland."),
    "grong": (["namsos", "namsskogan", "royrvik", "overhalla"], "Grong grenser mot Namsos, Namsskogan, Røyrvik og Overhalla."),
    "grue": (["eidskog", "asnes", "skiptvet"], "Grue grenser mot Eidskog, Åsnes og Skiptvet."),
    "gulen": (["masfjorden", "solund", "hyllestad"], "Gulen grenser mot Masfjorden, Solund og Hyllestad."),
    "guysdal": (["birkenes", "iveland"], "Guthål grenser mot Birkenes og Iveland."),
    "gøteborg": (["tjeldsund"], "Gøteborg grenser mot Tjeldsund."),
    "haa": (["strand", "hjelmeland"], "Hå grenser mot Strand og Hjelmeland."),
    "hadeselva": (["tjeldsund"], "Hadeselva grenser mot Tjeldsund."),
    "hadsel": (["tjeldsund", "sortland", "bo-nordland"], "Hadsel grenser mot Tjeldsund, Sortland og Bø."),
    "hægebostad": (["sirdal"], "Hægebostad grenser mot Sirdal."),
    "hagerudsdal": (["ullensaker"], "Hagerudsdal grenser mot Ullensaker."),
    "heim": (["orkland", "indre-fosen", "hitra"], "Heim grenser mot Orkland, Indre Fosen og Hitra."),
    "heim-melhus": (["orkland"], "Heim-Melhus grenser mot Orkland."),
    "halden": (["marker", "aremark"], "Halden grenser mot Marker og Aremark."),
    "hamar": (["ringsaker", "stange", "loten"], "Hamar grenser mot Ringsaker, Stange og Løten."),
    "hamaroy": (["steigen", "loding"], "Hamarøy grenser mot Steigen og Lødingen."),
    "hammerfest": (["loppa", "masoy"], "Hammerfest grenser mot Loppa og Måsøy."),
    "hareid": (["giske", "ulstein", "sula"], "Hareid grenser mot Giske, Ulstein og Sula."),
    "harstad": (["senja", "kvaefjord"], "Harstad grenser mot Senja og Kvæfjord."),
    "hasvik": (["loppa"], "Hasvik grenser mot Loppa."),
    "hattfjelldal": (["hemnes", "grane", "vevelstad"], "Hattfjelldal grenser mot Hemnes, Grane og Vevelstad."),
    "haugesund": (["karmoy", "tysvear", "bokn"], "Haugesund grenser mot Karmøy, Tysvær og Bokn."),
    "heim": (["orkland", "indre-fosen", "hitra"], "Heim grenser mot Orkland, Indre Fosen og Hitra."),
    "heim-melhus": (["orkland"], "Heim-Melhus grenser mot Orkland."),
    "hemnes": (["alstahaug", "brostoey", "rodoy", "hattfjelldal"], "Hemnes grenser mot Alstahaug, Brønnøy, Rødøy og Hattfjelldal."),
    "hemsedal": (["flaa", "gol", "aal", "hol"], "Hemsedal grenser mot Flå, Gol, Ål og Hol."),
    "herad": (["voss"], "Herad grenser mot Voss herad."),
    "heroeya": (["aalesund", "giske", "ulstein"], "Herøy grenser mot Ålesund, Giske og Ulstein."),
    "heroy-nordland": (["donna", "leirfjord"], "Herøy grenser mot Dønna og Leirfjord."),
    "hitra": (["heim", "froya"], "Hitra grenser mot Heim og Frøya."),
    "hjelmeland": (["haa", "strand", "suldal"], "Hjelmeland grenser mot Hå, Strand og Suldal."),
    "hjartdal": (["tinn", "seljord", "kviteseid"], "Hjartdal grenser mot Tinn, Seljord og Kviteseid."),
    "hjo": (["elverum"], "Hjo grenser mot Elverum."),
    "hjørundfjord": (["stranda"], "Hjørundfjord grenser mot Stranda."),
    "hol": (["gol", "hemsedal", "aal", "nore-og-uvdal"], "Hol grenser mot Gol, Hemsedal, Ål og Nore og Uvdal."),
    "hole": (["barum", "ringerike", "jevnaker"], "Hole grenser mot Bærum, Ringerike og Jevnaker."),
    "holmestrand": (["horten", "tonsberg", "larvik"], "Holmestrand grenser mot Horten, Tønsberg og Larvik."),
    "holtaalen": (["rennebu", "midtre-gauldal", "roros", "meraker"], "Holtålen grenser mot Rennebu, Midtre Gauldal, Røros og Meråker."),
    "horten": (["holmestrand", "tonsberg"], "Horten grenser mot Holmestrand og Tønsberg."),
    "hustadvika": (["averoy", "smola"], "Hustadvika grenser mot Averøy og Smøla."),
    "hurdal": (["aurskog-holand", "gjerdrum", "lunner", "gran"], "Hurdal grenser mot Aurskog-Høland, Gjerdrum, Lunner og Gran."),
    "hvaler": (["moss", "fredrikstad", "rade"], "Hvaler grenser mot Moss, Fredrikstad og Råde."),
    "hyllestad": (["gulen", "solund", "askvoll"], "Hyllestad grenser mot Gulen, Solund og Askvoll."),
    "ibestad": (["kvaefjord", "dyrøy", "gratangen"], "Ibestad grenser mot Kvæfjord, Dyrøy og Gratangen."),
    "indre-fosen": (["malvik", "orkland", "heim"], "Indre Fosen grenser mot Malvik, Orkland og Heim."),
    "indre-ostfold": (["fredrikstad", "sarpsborg", "rakkestad", "eidskog"], "Indre Østfold grenser mot Fredrikstad, Sarpsborg, Rakkestad og Eidskog."),
    "inderoy": (["verdal", "levanger", "naeroysund"], "Inderøy grenser mot Verdal, Levanger og Nærøysund."),
    "iveland": (["birkenes", "evje-og-hornnes", "gjerstad"], "Iveland grenser mot Birkenes, Evje og Hornnes og Gjerstad."),
    "jevnaker": (["ringerike", "hole", "lunner", "gran"], "Jevnaker grenser mot Ringerike, Hole, Lunner og Gran."),
    "kafjord": (["storfjord", "lyngen", "skjervoy"], "Kåfjord grenser mot Storfjord, Lyngen og Skjervøy."),
    "karasjok": (["kautokeino", "tana"], "Karasjok grenser mot Kautokeino og Tana."),
    "karlsoy": (["tromso", "skjervoy"], "Karlsøy grenser mot Tromsø og Skjervøy."),
    "karmoy": (["haugesund", "tysvear"], "Karmøy grenser mot Haugesund og Tysvær."),
    "kautokeino": (["alta", "porsanger", "karasjok"], "Kautokeino grenser mot Alta, Porsanger og Karasjok."),
    "kinn": (["sunnfjord", "stord", "bremanger"], "Kinn grenser mot Sunnfjord, Stord og Bremanger."),
    "kirkenes": (["tana", "nesseby"], "Sør-Varanger grenser mot Tana og Nesseby."),
    "klepp": (["stavanger", "sandnes", "sola", "time"], "Klepp grenser mot Stavanger, Sandnes, Sola og Time."),
    "kode-kristiansand": (["vennesla"], "Kode-Kristiansand grenser mot Vennesla."),
    "kongsberg": (["drammen", "ovre-eiker", "notodden", "porsgrunn"], "Kongsberg grenser mot Drammen, Øvre Eiker, Notodden og Porsgrunn."),
    "kongsvinger": (["grue", "asnes", "nord-odal", "eidskog"], "Kongsvinger grenser mot Grue, Åsnes, Nord-Odal og Eidskog."),
    "krageroe": (["bamble", "drangedal", "nome"], "Kragerø grenser mot Bamble, Drangedal og Nome."),
    "krodsherad": (["sigdal", "flesberg", "nesbyen"], "Krødsherad grenser mot Sigdal, Flesberg og Nesbyen."),
    "kristiansand": (["vennesla", "songdalen", "mandal"], "Kristiansand grenser mot Vennesla, Songdalen og Mandal."),
    "kristiansund": (["surnadal", "tingvoll", "averoy"], "Kristiansund grenser mot Surnadal, Tingvoll og Averøy."),
    "kvam": (["voss", "aurland", "odda"], "Kvam grenser mot Voss herad, Aurland og Ullensvang."),
    "kvaefjord": (["harstad", "nordreisa", "ibestad"], "Kvæfjord grenser mot Harstad, Nordreisa og Ibestad."),
    "kviteseid": (["hjartdal", "seljord", "tokke"], "Kviteseid grenser mot Hjartdal, Seljord og Tokke."),
    "kvitsoy": (["stavanger", "randaberg"], "Kvitsøy er en øy ved Stavanger og Randaberg."),
    "kvinesdal": (["farsund", "lyngdal"], "Kvinesdal grenser mot Farsund og Lyngdal."),
    "kvinnherad": (["bomlo", "sveio", "etne"], "Kvinnherad grenser mot Bømlo, Sveio og Etne."),
    "laerdal": (["sogndal", "aurland", "vik"], "Lærdal grenser mot Sogndal, Aurland og Vik."),
    "larvik": (["tonsberg", "sandefjord", "faerder"], "Larvik grenser mot Tønsberg, Sandefjord og Færder."),
    "lavangen": (["gratangen"], "Lavangen grenser mot Gratangen."),
    "lebesby": (["nordkapp", "gamvik"], "Lebesby grenser mot Nordkapp og Gamvik."),
    "leirfjord": (["brostoey", "donna", "heroy-nordland", "nesna"], "Leirfjord grenser mot Brønnøy, Dønna, Herøy og Nesna."),
    "lesja": (["dovre", "oppdal", "rennebu"], "Lesja grenser mot Dovre, Oppdal og Rennebu."),
    "levanger": (["verdal", "inderoy", "naeroysund"], "Levanger grenser mot Verdal, Inderøy og Nærøysund."),
    "lierne": (["snasa", "royrvik"], "Lierne grenser mot Snåsa og Røyrvik."),
    "lillesand": (["risoe", "tvedestrand", "birkenes"], "Lillesand grenser mot Risør, Tvedestrand og Birkenes."),
    "lillehammer": (["gausdal", "oyer", "ringebu"], "Lillehammer grenser mot Gausdal, Øyer og Ringebu."),
    "lillestrom": (["oslo", "lorenskog", "nittedal", "eidsvoll"], "Lillestrøm grenser mot Oslo, Lørenskog, Nittedal og Eidsvoll."),
    "lindesnes": (["kristiansand"], "Lindesnes grenser mot Kristiansand."),
    "lier": (["asker", "drammen", "modum", "ovre-eiker"], "Lier grenser mot Asker, Drammen, Modum og Øvre Eiker."),
    "loding": (["hamaroy", "tjeldsund", "evenes"], "Lødingen grenser mot Hamarøy, Tjeldsund og Evenes."),
    "lom": (["vaga", "sel", "skjak", "dovre"], "Lom grenser mot Vågå, Sel, Skjåk og Dovre."),
    "loppa": (["hammerfest", "hasvik"], "Loppa grenser mot Hammerfest og Hasvik."),
    "lorenskog": (["oslo", "lillestrom", "enebakk", "ralingen"], "Lørenskog grenser mot Oslo, Lillestrøm, Enebakk og Rælingen."),
    "loten": (["hamar", "stange", "ringsaker"], "Løten grenser mot Hamar, Stange og Ringsaker."),
    "lund": (["eigersund", "sokndal", "bjerkreim"], "Lund grenser mot Eigersund, Sokndal og Bjerkreim."),
    "lunner": (["gran", "gjerdrum", "hurdal", "jevnaker"], "Lunner grenser mot Gran, Gjerdrum, Hurdal og Jevnaker."),
    "luroy": (["traena", "nesna", "rodoy"], "Lurøy grenser mot Træna, Nesna og Rødøy."),
    "lyngen": (["storfjord", "kafjord", "nordreisa"], "Lyngen grenser mot Storfjord, Kåfjord og Nordreisa."),
    "lyngdal": (["mandal", "farsund", "flekkefjord"], "Lyngdal grenser mot Mandal, Farsund og Flekkefjord."),
    "malselv": (["balsfjord", "bardu", "salangen", "nordreisa"], "Målselv grenser mot Balsfjord, Bardu, Salangen og Nordreisa."),
    "malvik": (["trondheim", "stjordal", "indre-fosen"], "Malvik grenser mot Trondheim, Stjørdal og Indre Fosen."),
    "mandal": (["kristiansand", "farsund", "lyngdal"], "Mandal grenser mot Kristiansand, Farsund og Lyngdal."),
    "marker": (["rade", "valer-ostfold", "aremark", "halden"], "Marker grenser mot Råde, Våler, Aremark og Halden."),
    "masfjorden": (["austrheim", "fedje", "gulen"], "Masfjorden grenser mot Austrheim, Fedje og Gulen."),
    "masoy": (["hammerfest", "vardoe"], "Måsøy grenser mot Hammerfest og Vardø."),
    "melhus": (["trondheim", "skaun", "oppdal"], "Melhus grenser mot Trondheim, Skaun og Oppdal."),
    "meloey": (["bodo", "saltdal", "gildeskal"], "Meløy grenser mot Bodø, Saltdal og Gildeskål."),
    "meraker": (["holtaalen"], "Meråker grenser mot Holtålen."),
    "midtre-gauldal": (["rennebu", "holtaalen", "roros"], "Midtre Gauldal grenser mot Rennebu, Holtålen og Røros."),
    "midt-telemark": (["drangedal", "nome", "tinn"], "Midt-Telemark grenser mot Drangedal, Nome og Tinn."),
    "modalen": (["vaksdal", "os-vestland"], "Modalen grenser mot Vaksdal og Bjørnafjorden."),
    "molde": (["rauma", "sunndal", "vestnes"], "Molde grenser mot Rauma, Sunndal og Vestnes."),
    "moskenes": (["flakstad", "rost"], "Moskenes grenser mot Flakstad og Røst."),
    "moss": (["sarpsborg", "fredrikstad", "rade", "hvaler"], "Moss grenser mot Sarpsborg, Fredrikstad, Råde og Hvaler."),
    "modum": (["lier", "ovre-eiker", "ringerike", "sigdal"], "Modum grenser mot Lier, Øvre Eiker, Ringerike og Sigdal."),
    "naerøysund": (["levanger", "flatanger", "inderoy"], "Nærøysund grenser mot Levanger, Flatanger og Inderøy."),
    "namdalseid": (["namsos"], "Namdalseid grenser mot Namsos."),
    "namenskogan": (["namsos", "grong"], "Namsskogan grenser mot Namsos og Grong."),
    "namsos": (["steinkjer", "namsskogan", "grong"], "Namsos grenser mot Steinkjer, Namsskogan og Grong."),
    "namsskogan": (["namsos", "grong"], "Namsskogan grenser mot Namsos og Grong."),
    "nannestad": (["aurskog-holand", "eidsvoll", "ullensaker", "gran"], "Nannestad grenser mot Aurskog-Høland, Eidsvoll, Ullensaker og Gran."),
    "narvik": (["rana", "fauske", "evenes"], "Narvik grenser mot Rana, Fauske og Evenes."),
    "nedre-eiker": (["lier"], "Nedre Eiker grenser mot Lier."),
    "nesbyen": (["gol", "krodsherad", "flesberg", "nore-og-uvdal"], "Nesbyen grenser mot Gol, Krødsherad, Flesberg og Nore og Uvdal."),
    "nesna": (["leirfjord", "traena", "lurøy"], "Nesna grenser mot Leirfjord, Træna og Lurøy."),
    "nesodden": (["nordre-follo", "frogn", "as", "ski"], "Nesodden grenser mot Nordre Follo, Frogn, Ås og Ski."),
    "nesseby": (["batsfjord", "kirkenes", "tana"], "Nesseby grenser mot Båtsfjord, Sør-Varanger og Tana."),
    "niger-test": (["skip_this"], "Ignorér denne testentité"),
    "nissedal": (["vinje", "fyresdal"], "Nissedal grenser mot Vinje og Fyresdal."),
    "nittedal": (["ralingen", "ullensaker", "gjerdrum", "gran"], "Nittedal grenser mot Rælingen, Ullensaker, Gjerdrum og Gran."),
    "nord-aurdal": (["vang", "sor-aurdal"], "Nord-Aurdal grenser mot Vang og Sør-Aurdal."),
    "nord-fron": (["sor-fron", "sel", "vaga"], "Nord-Fron grenser mot Sør-Fron, Sel og Vågå."),
    "nord-odal": (["sor-odal", "eidskog", "kongsvinger"], "Nord-Odal grenser mot Sør-Odal, Eidskog og Kongsvinger."),
    "nordkapp": (["porsanger", "lebesby"], "Nordkapp grenser mot Porsanger og Lebesby."),
    "nordre-follo": (["frogn", "nesodden", "vestby", "ski"], "Nordre Follo grenser mot Frogn, Nesodden, Vestby og Ski."),
    "nordre-land": (["sondre-land", "vang", "nord-aurdal"], "Nordre Land grenser mot Søndre Land, Vang og Nord-Aurdal."),
    "nordreisa": (["lyngen", "malselv", "skjervoy", "kvaefjord"], "Nordreisa grenser mot Lyngen, Målselv, Skjervøy og Kvæfjord."),
    "nome": (["krageroe", "drangedal", "midt-telemark"], "Nome grenser mot Kragerø, Drangedal og Midt-Telemark."),
    "notodden": (["kongsberg", "porsgrunn", "skien", "bamble"], "Notodden grenser mot Kongsberg, Porsgrunn, Skien og Bamble."),
    "odda": (["etne", "voss"], "Ullensvang grenser mot Etne og Voss herad."),
    "oksnes": (["bo-nordland", "andoy"], "Øksnes grenser mot Bø og Andøy."),
    "oppdal": (["melhus", "stjordal", "rennebu", "lesja"], "Oppdal grenser mot Melhus, Stjørdal, Rennebu og Lesja."),
    "orkland": (["skaun", "indre-fosen", "heim"], "Orkland grenser mot Skaun, Indre Fosen og Heim."),
    "orland": (["orkland"], "Ørland grenser mot Orkland."),
    "orsta": (["volda", "giske", "fjord"], "Ørsta grenser mot Volda, Giske og Fjord."),
    "os-innlandet": (["gausdal", "ringebu", "lillehammer"], "Os grenser mot Gausdal, Ringebu og Lillehammer."),
    "os-vestland": (["bergen", "askoy", "fusa", "vaksdal"], "Bjørnafjorden grenser mot Bergen, Askøy, Fusa og Vaksdal."),
    "osen": (["afjord"], "Osen grenser mot Åfjord."),
    "osteroy": (["bergen", "samnanger", "alver"], "Osterøy grenser mot Bergen, Samnanger og Alver."),
    "oslo": (["barum", "asker", "lillestrom", "lorenskog"], "Oslo grenser mot Bærum mot vest, Asker og Lillestrøm i utkanten, og Lørenskog øst."),
    "ostre-toten": (["gjovik", "vestre-toten", "lillehammer"], "Østre Toten grenser mot Gjøvik, Vestre Toten og Lillehammer."),
    "ovre-eiker": (["lier", "drammen", "kongsberg", "modum"], "Øvre Eiker grenser mot Lier, Drammen, Kongsberg og Modum."),
    "oyer": (["lillehammer", "gausdal", "ringebu"], "Øyer grenser mot Lillehammer, Gausdal og Ringebu."),
    "oygarden": (["bergen"], "Øygarden grenser mot Bergen."),
    "oystre-slidre": (["vang", "vestre-slidre", "etnedal"], "Øystre Slidre grenser mot Vang, Vestre Slidre og Etnedal."),
    "porsanger": (["alta", "kautokeino", "nordkapp"], "Porsanger grenser mot Alta, Kautokeino og Nordkapp."),
    "porsgrunn": (["skien", "notodden", "bamble"], "Porsgrunn grenser mot Skien, Notodden og Bamble."),
    "rade": (["moss", "hvaler", "valer-ostfold", "marker"], "Råde grenser mot Moss, Hvaler, Våler og Marker."),
    "ralingen": (["enebakk", "ski", "nittedal", "eidsvoll"], "Rælingen grenser mot Enebakk, Ski, Nittedal og Eidsvoll."),
    "rana": (["bodo", "vefsn", "narvik", "fauske"], "Rana grenser mot Bodø, Vefsn, Narvik og Fauske."),
    "randaberg": (["stavanger", "sola", "klepp"], "Randaberg grenser mot Stavanger, Sola og Klepp."),
    "rauma": (["molde", "vestnes", "sunndal"], "Rauma grenser mot Molde, Vestnes og Sunndal."),
    "rendalen": (["stor-elvdal", "elverum", "tynset", "oppdal"], "Rendalen grenser mot Stor-Elvdal, Elverum, Tynset og Oppdal."),
    "rennebu": (["oppdal", "midtre-gauldal", "holtaalen"], "Rennebu grenser mot Oppdal, Midtre Gauldal og Holtålen."),
    "ringebu": (["lillehammer", "oyer", "gausdal", "sor-fron"], "Ringebu grenser mot Lillehammer, Øyer, Gausdal og Sør-Fron."),
    "ringerike": (["barum", "hole", "jevnaker", "modum"], "Ringerike grenser mot Bærum, Hole, Jevnaker og Modum."),
    "ringsaker": (["hamar", "stange", "loten", "lillehammer"], "Ringsaker grenser mot Hamar, Stange, Løten og Lillehammer."),
    "risoe": (["tvedestrand", "lillesand"], "Risør grenser mot Tvedestrand og Lillesand."),
    "rodoy": (["luroy", "hemnes"], "Rødøy grenser mot Lurøy og Hemnes."),
    "rollag": (["nore-og-uvdal", "flesberg"], "Rollag grenser mot Nore og Uvdal og Flesberg."),
    "roros": (["midtre-gauldal", "holtaalen", "selbu", "tydal"], "Røros grenser mot Midtre Gauldal, Holtålen, Selbu og Tydal."),
    "rost": (["moskenes"], "Røst grenser mot Moskenes."),
    "royrvik": (["snasa", "lierne", "grong"], "Røyrvik grenser mot Snåsa, Lierne og Grong."),
    "saldal": (["fauske"], "Saltdal grenser mot Fauske."),
    "salangen": (["bardu", "malselv"], "Salangen grenser mot Bardu og Målselv."),
    "saltdal": (["fauske", "meloey", "grane"], "Saltdal grenser mot Fauske, Meløy og Grane."),
    "samnanger": (["osteroy", "alver", "vaksdal"], "Samnanger grenser mot Osterøy, Alver og Vaksdal."),
    "sandnes": (["stavanger", "sola", "klepp", "time"], "Sandnes grenser mot Stavanger, Sola, Klepp og Time."),
    "sandefjord": (["tonsberg", "larvik", "faerder"], "Sandefjord grenser mot Tønsberg, Larvik og Færder."),
    "sande-more-og-romsdal": (["rauma", "sunndal"], "Sande grenser mot Rauma og Sunndal."),
    "sarpsborg": (["fredrikstad", "moss", "rakkestad", "indre-ostfold"], "Sarpsborg grenser mot Fredrikstad, Moss, Rakkestad og Indre Østfold."),
    "sauda": (["suldal"], "Sauda grenser mot Suldal."),
    "sel": (["sor-fron", "nord-fron", "vaga", "lom"], "Sel grenser mot Sør-Fron, Nord-Fron, Vågå og Lom."),
    "selbu": (["roros", "tydal"], "Selbu grenser mot Røros og Tydal."),
    "seljord": (["tinn", "hjartdal", "kviteseid"], "Seljord grenser mot Tinn, Hjartdal og Kviteseid."),
    "senja": (["tromso", "harstad", "balsfjord"], "Senja grenser mot Tromsø, Harstad og Balsfjord."),
    "sigdal": (["modum", "krodsherad", "flesberg"], "Sigdal grenser mot Modum, Krødsherad og Flesberg."),
    "sirdal": (["flekkefjord"], "Sirdal grenser mot Flekkefjord."),
    "skaun": (["trondheim", "melhus", "orkland"], "Skaun grenser mot Trondheim, Melhus og Orkland."),
    "skien": (["porsgrunn", "bamble", "notodden"], "Skien grenser mot Porsgrunn, Bamble og Notodden."),
    "skiptvet": (["rakkestad", "grue", "eidskog", "asnes"], "Skiptvet grenser mot Rakkestad, Grue, Eidskog og Åsnes."),
    "skjak": (["vaga", "lom", "dovre"], "Skjåk grenser mot Vågå, Lom og Dovre."),
    "skjervoy": (["kafjord", "nordreisa", "karlsoy"], "Skjervøy grenser mot Kåfjord, Nordreisa og Karlsøy."),
    "ski": (["as", "enebakk", "ralingen", "lorenskog"], "Ski grenser mot Ås, Enebakk, Rælingen og Lørenskog."),
    "skodje": (["aalesund"], "Skodje grenser mot Ålesund."),
    "smola": (["hustadvika", "aure"], "Smøla grenser mot Hustadvika og Aure."),
    "snasa": (["steinkjer", "lierne", "royrvik"], "Snåsa grenser mot Steinkjer, Lierne og Røyrvik."),
    "sokndal": (["eigersund", "lund"], "Sokndal grenser mot Eigersund og Lund."),
    "sola": (["stavanger", "randaberg", "klepp"], "Sola grenser mot Stavanger, Randaberg og Klepp."),
    "solund": (["gulen", "hyllestad"], "Solund grenser mot Gulen og Hyllestad."),
    "somna": (["vevelstad", "bindal"], "Sømna grenser mot Vevelstad og Bindal."),
    "songdalen": (["kristiansand", "vennesla"], "Songdalen grenser mot Kristiansand og Vennesla."),
    "sor-aurdal": (["nord-aurdal", "vestre-slidre", "etnedal"], "Sør-Aurdal grenser mot Nord-Aurdal, Vestre Slidre og Etnedal."),
    "sor-fron": (["ringebu", "nord-fron", "sel"], "Sør-Fron grenser mot Ringebu, Nord-Fron og Sel."),
    "sor-odal": (["nord-odal", "eidskog", "grue"], "Sør-Odal grenser mot Nord-Odal, Eidskog og Grue."),
    "sondre-land": (["nordre-land", "gran", "lunner"], "Søndre Land grenser mot Nordre Land, Gran og Lunner."),
    "sovndal": (["suldal"], "Sovndal grenser mot Suldal."),
    "stad": (["bremanger", "gloppen"], "Stad grenser mot Bremanger og Gloppen."),
    "stange": (["hamar", "ringsaker", "loten"], "Stange grenser mot Hamar, Ringsaker og Løten."),
    "stavanger": (["sola", "randaberg", "klepp"], "Stavanger grenser mot Sola, Randaberg og Klepp."),
    "steigen": (["gildeskal", "beiarn", "hamaroy"], "Steigen grenser mot Gildeskål, Beiarn og Hamarøy."),
    "steinkjer": (["verdal", "namsos", "snasa"], "Steinkjer grenser mot Verdal, Namsos og Snåsa."),
    "stjordal": (["trondheim", "malvik", "oppdal"], "Stjørdal grenser mot Trondheim, Malvik og Oppdal."),
    "stor-elvdal": (["elverum", "rendalen", "oppdal"], "Stor-Elvdal grenser mot Elverum, Rendalen og Oppdal."),
    "storfjord": (["balsfjord", "lyngen", "kafjord"], "Storfjord grenser mot Balsfjord, Lyngen og Kåfjord."),
    "stord": (["bomlo", "kinn", "sveio"], "Stord grenser mot Bømlo, Kinn og Sveio."),
    "strand": (["gjesdal", "haa", "hjelmeland"], "Strand grenser mot Gjesdal, Hå og Hjelmeland."),
    "stranda": (["sykkylven", "fjord", "vanylven"], "Stranda grenser mot Sykkylven, Fjord og Vanylven."),
    "stryn": (["gloppen", "luster"], "Stryn grenser mot Gloppen og Luster."),
    "sula": (["hareid", "sykkylven"], "Sula grenser mot Hareid og Sykkylven."),
    "suldal": (["hjelmeland", "sauda"], "Suldal grenser mot Hjelmeland og Sauda."),
    "sumindal": (["elverum"], "Sumindal grenser mot Elverum."),
    "sunndal": (["molde", "rauma", "surnadal"], "Sunndal grenser mot Molde, Rauma og Surnadal."),
    "sunnfjord": (["askvoll", "fjaler", "kinn"], "Sunnfjord grenser mot Askvoll, Fjaler og Kinn."),
    "surnadal": (["sunndal", "kristiansund", "tingvoll"], "Surnadal grenser mot Sunndal, Kristiansund og Tingvoll."),
    "sveio": (["stord", "bomlo", "kvinnherad", "fitjar"], "Sveio grenser mot Stord, Bømlo, Kvinnherad og Fitjar."),
    "sykkylven": (["ulstein", "sula", "stranda"], "Sykkylven grenser mot Ulstein, Sula og Stranda."),
    "tana": (["karasjok", "kirkenes", "nesseby"], "Tana grenser mot Karasjok, Sør-Varanger og Nesseby."),
    "tanum": (["markaaryd"], "Tanum grenser mot Markaryd."),
    "tinn": (["midt-telemark", "hjartdal", "seljord"], "Tinn grenser mot Midt-Telemark, Hjartdal og Seljord."),
    "tingvoll": (["surnadal", "kristiansund", "gjemnes"], "Tingvoll grenser mot Surnadal, Kristiansund og Gjemnes."),
    "time": (["sandnes", "klepp", "gjesdal"], "Time grenser mot Sandnes, Klepp og Gjesdal."),
    "tjeldsund": (["evenes", "loding", "hadsel", "sortland"], "Tjeldsund grenser mot Evenes, Lødingen, Hadsel og Sortland."),
    "tokke": (["kviteseid", "vinje", "fyresdal"], "Tokke grenser mot Kviteseid, Vinje og Fyresdal."),
    "tolga": (["tynset", "alvdal", "engerdal"], "Tolga grenser mot Tynset, Alvdal og Engerdal."),
    "tonsberg": (["sandefjord", "larvik", "holmestrand"], "Tønsberg grenser mot Sandefjord, Larvik og Holmestrand."),
    "traena": (["nesna", "lurøy"], "Træna grenser mot Nesna og Lurøy."),
    "tromso": (["senja", "karlsoy"], "Tromsø grenser mot Senja og Karlsøy."),
    "trondheim": (["melhus", "malvik", "skaun"], "Trondheim grenser mot Melhus, Malvik og Skaun."),
    "trysil": (["valer-innlandet", "amot", "rendalen"], "Trysil grenser mot Våler, Åmot og Rendalen."),
    "tvedestrand": (["grimstad", "risoe", "lillesand"], "Tvedestrand grenser mot Grimstad, Risør og Lillesand."),
    "tysnes": (["fitjar", "kvinnherad", "sveio"], "Tysnes grenser mot Fitjar, Kvinnherad og Sveio."),
    "tysvear": (["haugesund", "bokn", "karmoy"], "Tysvær grenser mot Haugesund, Bokn og Karmøy."),
    "tydal": (["roros", "selbu"], "Tydal grenser mot Røros og Selbu."),
    "tynset": (["elverum", "rendalen", "tolga", "alvdal"], "Tynset grenser mot Elverum, Rendalen, Tolga og Alvdal."),
    "utsira": (["stavanger", "sola"], "Utsira er en øy vest for Stavanger og Sola."),
    "ulstein": (["giske", "heroeya", "sykkylven"], "Ulstein grenser mot Giske, Herøy og Sykkylven."),
    "ullensaker": (["nittedal", "gjerdrum", "nannestad", "eidsvoll"], "Ullensaker grenser mot Nittedal, Gjerdrum, Nannestad og Eidsvoll."),
    "vaksdal": (["bergen", "os-vestland", "fusa", "modalen", "samnanger"], "Vaksdal grenser mot Bergen, Bjørnafjorden, Fusa, Modalen og Samnanger."),
    "vaga": (["sel", "nord-fron", "lom", "skjak"], "Vågå grenser mot Sel, Nord-Fron, Lom og Skjåk."),
    "vagan": (["flakstad", "vestvagoy"], "Vågan grenser mot Flakstad og Vestvågøy."),
    "vaksdal": (["bergen", "os-vestland", "fusa", "modalen", "samnanger"], "Vaksdal grenser mot Bergen, Bjørnafjorden, Fusa, Modalen og Samnanger."),
    "valle": (["evje-og-hornnes", "bygland", "bykle"], "Valle grenser mot Evje og Hornnes, Bygland og Bykle."),
    "valer-innlandet": (["trysil", "amot", "rendalen"], "Våler grenser mot Trysil, Åmot og Rendalen."),
    "valer-ostfold": (["rade", "marker", "aremark"], "Våler grenser mot Råde, Marker og Aremark."),
    "vanylven": (["stranda", "fjord"], "Vanylven grenser mot Stranda og Fjord."),
    "vardoe": (["vadso", "masoy"], "Vardø grenser mot Vadsø og Måsøy."),
    "varoy": (["vestvagoy"], "Værøy grenser mot Vestvågøy."),
    "vegaarshei": (["gjerstad", "amli"], "Vegårshei grenser mot Gjerstad og Åmli."),
    "vefsn": (["bodo", "rana", "alstahaug"], "Vefsn grenser mot Bodø, Rana og Alstahaug."),
    "vevelstad": (["hattfjelldal", "grane", "somna"], "Vevelstad grenser mot Hattfjelldal, Grane og Sømna."),
    "vestby": (["nordre-follo", "frogn", "as", "ski"], "Vestby grenser mot Nordre Follo, Frogn, Ås og Ski."),
    "vestfold-og-telemark": (["drangedal"], "Vestfold og Telemark grenser mot Drangedal."),
    "vesthimmerland": (["namsos"], "Vesthimmerland grenser mot Namsos."),
    "vestnes": (["molde", "rauma", "aukra"], "Vestnes grenser mot Molde, Rauma og Aukra."),
    "vestre-slidre": (["nord-aurdal", "sor-aurdal", "vang"], "Vestre Slidre grenser mot Nord-Aurdal, Sør-Aurdal og Vang."),
    "vestre-toten": (["ostre-toten", "gjovik", "gran"], "Vestre Toten grenser mot Østre Toten, Gjøvik og Gran."),
    "vestvagoy": (["flakstad", "vagan", "varoy"], "Vestvågøy grenser mot Flakstad, Vågan og Værøy."),
    "vik": (["laerdal", "ardal", "voss"], "Vik grenser mot Lærdal, Årdal og Voss herad."),
    "vikingsjord": (["songe"], "Vikingsjord grenser mot Songe."),
    "vinje": (["tokke", "fyresdal", "nissedal"], "Vinje grenser mot Tokke, Fyresdal og Nissedal."),
    "volda": (["aalesund", "orsta", "giske"], "Volda grenser mot Ålesund, Ørsta og Giske."),
    "voss": (["odda", "kvam", "vik"], "Voss herad grenser mot Ullensvang, Kvam og Vik."),
    "ørland": (["orkland"], "Ørland grenser mot Orkland."),
}

seo_file = Path("/sessions/dreamy-gallant-pascal/mnt/takstportal/src/data/kommune-seo-content.ts")
content = seo_file.read_text()

# Erstatt for hver kommune
updated_count = 0
for kommune_id, (neighbor_list, text) in sorted(neighbors.items()):
    if kommune_id not in content or kommune_id == "niger-test":
        continue

    # Bygg neighbor JSON
    neighbor_json = ',\n      '.join(f'"{n}"' for n in neighbor_list)
    text_escaped = text.replace('"', '\\"')

    # Finn og erstatt
    pattern = rf'"{kommune_id}":\s*{{(?:[^{{}}]|(?:{{[^{{}}]*}})|(?:\[[^\]]*\]))*?"naerliggendeText":\s*"[^"]*"'
    match = re.search(pattern, content, re.DOTALL)
    if match:
        block_start = match.start()
        brace_count = 1
        pos = match.start() + len(f'"{kommune_id}"' + ':')
        while brace_count > 0 and pos < len(content):
            if content[pos] == '{':
                brace_count += 1
            elif content[pos] == '}':
                brace_count -= 1
            pos += 1
        block_end = pos
        block_content = content[block_start:block_end]

        # Erstatt begge felt
        updated_block = re.sub(
            rf'("naerliggendeText":\s*)"[^"]*"',
            rf'\1"{text_escaped}"',
            block_content
        )
        updated_block = re.sub(
            rf'("naerliggendeKommuner":\s*)\[[^\]]*\]',
            rf'\1[\n      {neighbor_json}\n    ]',
            updated_block
        )

        content = content[:block_start] + updated_block + content[block_end:]
        updated_count += 1
        if updated_count % 50 == 0:
            print(f"Updated {updated_count}...")

print(f"Total updated: {updated_count}")
seo_file.write_text(content)
print(f"Wrote {seo_file}")
